name: smartparking
description: Smart parking application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: ^1.1.2
  fluttertoast: ^8.0.9
  flutter_barcode_scanner: ^2.0.0
  flutter_beep: ^1.0.0
  shared_preferences: ^2.0.15
  esc_pos_printer: ^4.1.0
  blue_thermal_printer: ^1.2.2
  path_provider: ^2.0.11
  provider: ^6.0.3
  animated_splash_screen: ^1.3.0
  web_socket_channel: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1


flutter:

  uses-material-design: true

  assets:
    - 20945486.jpg
    - index.png



